//! Well-known IMAP/SMTP presets. We do not host mail.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProviderKind {
    Gmail,
    Outlook,
    Icloud,
    Fastmail,
    Yahoo,
    ProtonBridge,
    Custom,
    Tutanota,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProviderPreset {
    pub kind: ProviderKind,
    pub id: &'static str,
    pub label: &'static str,
    pub imap_host: &'static str,
    pub imap_port: u16,
    pub imap_tls: &'static str,
    pub smtp_host: &'static str,
    pub smtp_port: u16,
    pub smtp_tls: &'static str,
    pub auth_method: &'static str,
    pub unsupported: bool,
    pub notes: &'static str,
}

pub fn preset(kind: ProviderKind) -> ProviderPreset {
    match kind {
        ProviderKind::Gmail => ProviderPreset {
            kind,
            id: "gmail",
            label: "Gmail / Google Workspace",
            imap_host: "imap.gmail.com",
            imap_port: 993,
            imap_tls: "ssl",
            smtp_host: "smtp.gmail.com",
            smtp_port: 587,
            smtp_tls: "starttls",
            auth_method: "app-password",
            unsupported: false,
            notes: "Use a Google app password until OAuth2 ships. We never host Gmail.",
        },
        ProviderKind::Outlook => ProviderPreset {
            kind,
            id: "outlook",
            label: "Outlook / Microsoft 365",
            imap_host: "outlook.office365.com",
            imap_port: 993,
            imap_tls: "ssl",
            smtp_host: "smtp.office365.com",
            smtp_port: 587,
            smtp_tls: "starttls",
            auth_method: "app-password",
            unsupported: false,
            notes:
                "Many work tenants require OAuth2. App password works on some consumer accounts.",
        },
        ProviderKind::Icloud => ProviderPreset {
            kind,
            id: "icloud",
            label: "iCloud",
            imap_host: "imap.mail.me.com",
            imap_port: 993,
            imap_tls: "ssl",
            smtp_host: "smtp.mail.me.com",
            smtp_port: 587,
            smtp_tls: "starttls",
            auth_method: "app-password",
            unsupported: false,
            notes: "Apple app-specific password required.",
        },
        ProviderKind::Fastmail => ProviderPreset {
            kind,
            id: "fastmail",
            label: "Fastmail",
            imap_host: "imap.fastmail.com",
            imap_port: 993,
            imap_tls: "ssl",
            smtp_host: "smtp.fastmail.com",
            smtp_port: 587,
            smtp_tls: "starttls",
            auth_method: "password",
            unsupported: false,
            notes: "IMAP now. JMAP can come later.",
        },
        ProviderKind::Yahoo => ProviderPreset {
            kind,
            id: "yahoo",
            label: "Yahoo",
            imap_host: "imap.mail.yahoo.com",
            imap_port: 993,
            imap_tls: "ssl",
            smtp_host: "smtp.mail.yahoo.com",
            smtp_port: 587,
            smtp_tls: "starttls",
            auth_method: "app-password",
            unsupported: false,
            notes: "Yahoo app password required.",
        },
        ProviderKind::ProtonBridge => ProviderPreset {
            kind,
            id: "proton-bridge",
            label: "Proton Mail (via Bridge)",
            imap_host: "127.0.0.1",
            imap_port: 1143,
            imap_tls: "starttls",
            smtp_host: "127.0.0.1",
            smtp_port: 1025,
            smtp_tls: "starttls",
            auth_method: "bridge",
            unsupported: false,
            notes: "Install Proton Bridge first. We do not speak Proton's native API.",
        },
        ProviderKind::Custom => ProviderPreset {
            kind,
            id: "custom",
            label: "Custom IMAP / SMTP",
            imap_host: "",
            imap_port: 993,
            imap_tls: "ssl",
            smtp_host: "",
            smtp_port: 587,
            smtp_tls: "starttls",
            auth_method: "password",
            unsupported: false,
            notes: "Any domain that already gives you IMAP. We do not host the mailbox.",
        },
        ProviderKind::Tutanota => ProviderPreset {
            kind,
            id: "tutanota",
            label: "Tutanota",
            imap_host: "",
            imap_port: 0,
            imap_tls: "",
            smtp_host: "",
            smtp_port: 0,
            smtp_tls: "",
            auth_method: "",
            unsupported: true,
            notes: "No standard IMAP. Not supported.",
        },
    }
}

pub fn all_presets() -> Vec<ProviderPreset> {
    [
        ProviderKind::Gmail,
        ProviderKind::Outlook,
        ProviderKind::Icloud,
        ProviderKind::Fastmail,
        ProviderKind::Yahoo,
        ProviderKind::ProtonBridge,
        ProviderKind::Custom,
        ProviderKind::Tutanota,
    ]
    .into_iter()
    .map(preset)
    .collect()
}
